//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by myrosot1.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MYROSOT1_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       129
#define IDB_BITMAP1                     130
#define IDD_ADJUSTCOLOURS_DIALOG        131
#define IDD_RFCOMM_DIALOG               132
#define IDD_PARAMETERS_DIALOG           135
#define IDD_ADJUSTGAMEAREA_DIALOG       136
#define IDD_GRABBERSETTINGS_DIALOG      137
#define IDD_TUNING_DIALOG               138
#define IDD_TESTING_DIALOG              139
#define IDC_MAPCOLOURS_RADIO            1004
#define IDC_SETBOUNDARIES_RADIO         1005
#define IDC_FIELDAREA_RADIO             1006
#define IDC_HOMEGOALAREA_RADIO          1007
#define IDC_OPPOGOALAREA_RADIO          1008
#define IDC_R_EDIT                      1009
#define IDC_G_EDIT                      1010
#define IDC_B_EDIT                      1011
#define IDC_BALL_RADIO                  1013
#define IDC_ROBOT1_RADIO                1015
#define IDC_ROBOT2_RADIO                1016
#define IDC_TEAM_RADIO                  1017
#define IDC_LEFT_RADIO                  1030
#define IDC_RIGHT_RADIO                 1031
#define IDC_START_BUTTON                1032
#define IDC_STOP_BUTTON                 1033
#define IDC_TEST_BUTTON                 1034
#define IDC_STOPTEST_BUTTON             1036
#define IDC_BLACKBACKGROUND_CHECK       1037
#define IDC_GETREADY_BUTTON             1039
#define IDC_SAVECOLORS_BUTTON           1040
#define IDC_LOADCOLOURS_BUTTON          1041
#define IDC_BALLY_EDIT                  1042
#define IDC_ROBOT1Y_EDIT                1043
#define IDC_ROBOT2Y_EDIT                1044
#define IDC_GOALIEY_EDIT                1045
#define IDC_BALLX_EDIT                  1046
#define IDC_ROBOT1X_EDIT                1047
#define IDC_ROBOT2X_EDIT                1048
#define IDC_GOALIEX_EDIT                1049
#define IDC_ROBOT1ANGLE_EDIT            1050
#define IDC_ROBOT2ANGLE_EDIT            1051
#define IDC_GOALIEANGLE_EDIT            1052
#define IDC_TEAM_EDIT                   1053
#define IDC_TEAMFULL_EDIT               1054
#define IDC_BALL_EDIT                   1055
#define IDC_BALLFULL_EDIT               1056
#define IDC_FRAMECOUNT_EDIT             1057
#define IDC_FULLSCAN_EDIT               1058
#define IDC_OFF_RADIO                   1060
#define IDC_LOW_RADIO                   1061
#define IDC_HIGH_RADIO                  1062
#define IDC_ADJUSTRANGE_BUTTON          1063
#define IDC_BALLCOLYMIN_SCROLLBAR       1064
#define IDC_BALLCOLYMAX_SCROLLBAR       1065
#define IDC_BALLCOLUMIN_SCROLLBAR       1066
#define IDC_BALLCOLUMAX_SCROLLBAR       1067
#define IDC_BALLCOLVMIN_SCROLLBAR       1068
#define IDC_BALLCOLVMAX_SCROLLBAR       1069
#define IDC_BALLCOLYMIN_EDIT            1070
#define IDC_BALLCOLYMAX_EDIT            1071
#define IDC_BALLCOLUMIN_EDIT            1072
#define IDC_BALLCOLUMAX_EDIT            1073
#define IDC_BALLCOLVMIN_EDIT            1074
#define IDC_BALLCOLVMAX_EDIT            1075
#define IDC_UPDATELUT_BUTTON            1076
#define IDC_GOALIEL_SCROLLBAR           1077
#define IDC_GOALIER_SCROLLBAR           1078
#define IDC_GOALIEL_EDIT                1079
#define IDC_GOALIER_EDIT                1080
#define IDC_ROBOT1L_SCROLLBAR           1081
#define IDC_ROBOT1R_SCROLLBAR           1082
#define IDC_ROBOT1L_EDIT                1083
#define IDC_ROBOT1R_EDIT                1084
#define IDC_ROBOT2L_SCROLLBAR           1085
#define IDC_ROBOT2R_SCROLLBAR           1086
#define IDC_ROBOT2L_EDIT                1087
#define IDC_ROBOT2R_EDIT                1088
#define IDC_ROBOT2COLYMIN_SCROLLBAR     1089
#define IDC_SEND_BUTTON                 1089
#define IDC_ROBOT2COLYMAX_SCROLLBAR     1090
#define IDC_TURNLEFT_BUTTON             1090
#define IDC_ROBOT2COLUMIN_SCROLLBAR     1091
#define IDC_SPEED_SCROLLBAR             1091
#define IDC_ROBOT2COLUMAX_SCROLLBAR     1092
#define IDC_TURNRIGHT_BUTTON            1092
#define IDC_ROBOT2COLVMIN_SCROLLBAR     1093
#define IDC_FORWARD_BUTTON              1093
#define IDC_ROBOT2COLVMAX_SCROLLBAR     1094
#define IDC_REVERSE_BUTTON              1094
#define IDC_ROBOT2COLYMIN_EDIT          1095
#define IDC_SPEED_EDIT                  1095
#define IDC_OBSERVER_EDIT               1095
#define IDC_ROBOT2COLYMAX_EDIT          1096
#define IDC_ROBOT2COLUMIN_EDIT          1097
#define IDC_ROBOT2COLUMAX_EDIT          1098
#define IDC_MINPATCHSIZECOL1_SCROLLBAR  1098
#define IDC_ROBOT2COLVMIN_EDIT          1099
#define IDC_MINPATCHSIZECOL1_EDIT       1099
#define IDC_ROBOT2COLVMAX_EDIT          1100
#define IDC_LEFT_LEFT_BUTTON            1100
#define IDC_LEFT_RIGHT_BUTTON           1101
#define IDC_RIGHT_LEFT_BUTTON           1102
#define IDC_MINPATCHSIZECOL2_SCROLLBAR  1102
#define IDC_RIGHT_RIGHT_BUTTON          1103
#define IDC_MINPATCHSIZECOL2_EDIT       1103
#define IDC_TOP_UP_BUTTON               1104
#define IDC_GOALIEREMOVED_CHECK         1104
#define IDC_TOP_DOWN_BUTTON             1105
#define IDC_ROBOT1REMOVED_CHECK         1105
#define IDC_BOTTOM_UP_BUTTON            1106
#define IDC_ROBOT2REMOVED_CHECK         1106
#define IDC_BOTTOM_DOWN_BUTTON          1107
#define IDC_COM1_RADIO                  1107
#define IDC_COM2_RADIO                  1108
#define IDC_MINPATCHSIZETEAM_SCROLLBAR  1109
#define IDC_REMOVED_STATIC              1110
#define IDC_COMPORT_STATIC              1111
#define IDC_TEAMCOLYMIN_SCROLLBAR       1113
#define IDC_MINPATCHSIZECOL1_STATIC     1113
#define IDC_TEAMCOLYMAX_SCROLLBAR       1114
#define IDC_DISPLAY_CM_RADIO            1114
#define IDC_MINPATCHSIZECOL2_STATIC     1114
#define IDC_TEAMCOLUMIN_SCROLLBAR       1115
#define IDC_DISPLAY_PIXEL_RADIO         1115
#define IDC_MINPATCHSIZETEAM_STATIC     1115
#define IDC_TEAMCOLUMAX_SCROLLBAR       1116
#define IDC_FULLTRACKINGONLY_CHECK      1116
#define IDC_MINPATCHSIZETEAM_EDIT       1116
#define IDC_TEAMCOLVMIN_SCROLLBAR       1117
#define IDC_MINPATCHSIZEBALL_SCROLLBAR  1117
#define IDC_TEAMCOLVMAX_SCROLLBAR       1118
#define IDC_MINPATCHSIZEBALL_STATIC     1118
#define IDC_TEAMCOLYMIN_EDIT            1119
#define IDC_MINPATCHSIZEBALL_EDIT       1119
#define IDC_TEAMCOLYMAX_EDIT            1120
#define IDC_HUE_SCROLLBAR               1120
#define IDC_MINPATCHSIZEOPPO_SCROLLBAR  1120
#define IDC_TEAMCOLUMIN_EDIT            1121
#define IDC_SATURATION_SCROLLBAR        1121
#define IDC_MINPATCHSIZEOPPO_STATIC     1121
#define IDC_TEAMCOLUMAX_EDIT            1122
#define IDC_BRIGHTNESS_SCROLLBAR        1122
#define IDC_MINPATCHSIZEOPPO_EDIT       1122
#define IDC_TEAMCOLVMIN_EDIT            1123
#define IDC_CONTRAST_SCROLLBAR          1123
#define IDC_TEAMCOLVMAX_EDIT            1124
#define IDC_SHARPNESS_SCROLLBAR         1124
#define IDC_ROBOT1COLYMIN_SCROLLBAR     1125
#define IDC_HUE_EDIT                    1125
#define IDC_ROBOT1COLYMAX_SCROLLBAR     1126
#define IDC_SATURATION_EDIT             1126
#define IDC_ROBOT1COLUMIN_SCROLLBAR     1127
#define IDC_BRIGHTNESS_EDIT             1127
#define IDC_ROBOT1COLUMAX_SCROLLBAR     1128
#define IDC_CONTRAST_EDIT               1128
#define IDC_ROBOT1COLVMIN_SCROLLBAR     1129
#define IDC_SHARPNESS_EDIT              1129
#define IDC_ROBOT1COLVMAX_SCROLLBAR     1130
#define IDC_DEFAULT_BUTTON              1130
#define IDC_ROBOT1COLYMIN_EDIT          1131
#define IDC_KICKSTART_RADIO             1131
#define IDC_ROBOT1COLYMAX_EDIT          1132
#define IDC_GOALKICK_RADIO              1132
#define IDC_ROBOT1COLUMIN_EDIT          1133
#define IDC_PENALTY_RADIO               1133
#define IDC_ROBOT1COLUMAX_EDIT          1134
#define IDC_FREEKICK_RADIO              1134
#define IDC_ROBOT1COLVMIN_EDIT          1135
#define IDC_FREEBALL_RADIO              1135
#define IDC_ROBOT1COLVMAX_EDIT          1136
#define IDC_HOME_RADIO                  1136
#define IDC_OPPONENT_RADIO              1137
#define IDC_OPPOCOLYMIN_SCROLLBAR       1137
#define IDC_TOPLEFT_RADIO               1138
#define IDC_OPPOCOLYMAX_SCROLLBAR       1138
#define IDC_TOPRIGHT_RADIO              1139
#define IDC_OPPOCOLUMIN_SCROLLBAR       1139
#define IDC_BOTTOMLEFT_RADIO            1140
#define IDC_OPPOCOLUMAX_SCROLLBAR       1140
#define IDC_BOTTOMRIGHT_RADIO           1141
#define IDC_OPPOCOLVMIN_SCROLLBAR       1141
#define IDC_GO_BUTTON                   1142
#define IDC_OPPOCOLVMAX_SCROLLBAR       1142
#define IDC_OPPOCOLYMIN_EDIT            1143
#define IDC_OPPOCOLYMAX_EDIT            1144
#define IDC_OPPOCOLUMIN_EDIT            1145
#define IDC_OPPOCOLUMAX_EDIT            1146
#define IDC_OPPOCOLVMIN_EDIT            1147
#define IDC_OPPOCOLVMAX_EDIT            1148
#define IDC_CONSERVATIVE_RADIO          1164
#define IDC_NORMAL_RADIO                1165
#define IDC_AGGRESSIVE_RADIO            1166
#define IDC_GXCOMPENSATION_SCROLLBAR    1167
#define IDC_GXCOMPENSATION_EDIT         1168
#define IDC_PARALLAXCORRECTION_CHECK    1169
#define IDC_CAMERAHEIGHT_EDIT           1172
#define IDC_BALLCLEARTIME_SCROLLBAR     1174
#define IDC_BALLCLEARTIME_EDIT          1175
#define IDC_DISPLAY_HOME_RADIO          1176
#define IDC_KICKSTARTSPEED_SCROLLBAR    1176
#define IDC_DISPLAY_OPPO_RADIO          1177
#define IDC_KICKSTARTSPEED_EDIT         1177
#define IDC_KICKSTARTDISTANCE_SCROLLBAR 1178
#define IDC_KICKSTARTDISTANCE_EDIT      1179
#define IDC_GOALKICKSPEED_SCROLLBAR     1180
#define IDC_GOALKICKSPEED_EDIT          1181
#define IDC_GOALKICKDISTANCE_SCROLLBAR  1182
#define IDC_GOALKICKDISTANCE_EDIT       1183
#define IDC_OPPO_RADIO                  1184
#define IDC_PENALTYSPEED_SCROLLBAR      1184
#define IDC_TRACKOPPO_CHECK             1185
#define IDC_PENALTYSPEED_EDIT           1185
#define IDC_NUMOPPOROBOTS_SCROLLBAR     1186
#define IDC_PENALTYDISTANCE_SCROLLBAR   1186
#define IDC_NUMOPPOROBOTS_EDIT          1187
#define IDC_PENALTYDISTANCE_EDIT        1187
#define IDC_RADIO_CASE0                 1188
#define IDC_RADIO_CASE12                1189
#define IDC_COLORTUNING_CHECK           1191
#define IDC_RADIO_CASE1                 1192
#define IDC_STOPROBOTSWHENBALLLOST_CHECK 1192
#define IDC_RADIO_CASE2                 1193
#define IDC_FREEKICKSPEED_SCROLLBAR     1193
#define IDC_RADIO_CASE3                 1194
#define IDC_FREEKICKSPEED_EDIT          1194
#define IDC_RADIO_CASE4                 1195
#define IDC_FREEKICKDISTANCE_SCROLLBAR  1195
#define IDC_RADIO_CASE5                 1196
#define IDC_FREEKICKDISTANCE_EDIT       1196
#define IDC_RADIO_CASE6                 1197
#define IDC_FREEBALLSPEED_SCROLLBAR     1197
#define IDC_RADIO_CASE7                 1198
#define IDC_FREEBALLSPEED_EDIT          1198
#define IDC_RADIO_CASE8                 1199
#define IDC_FREEBALLDISTANCE_SCROLLBAR  1199
#define IDC_RADIO_CASE9                 1200
#define IDC_FREEBALLDISTANCE_EDIT       1200
#define IDC_RADIO_CASE10                1201
#define IDC_RADIO_CASE11                1202
#define IDC_QSTATE_BUTTON               1206
#define IDC_FOLLOWCLICK_CHECK           1207
#define IDC_ADJUSTBOUNDARY_STATIC       1215
#define IDC_DISPLAYBOUNDARIES_CHECK     1219
#define IDC_TIME_EDIT                   1220
#define ID_FILE_EXIT                    32771
#define ID_HELP_ABOUT                   32772
#define ID_UTILS_RFCOMM                 32780
#define ID_UTILS_SETPARAMETERS          32781
#define ID_UTILS_ADJUSTGAMEAREA         32782
#define ID_GRABBER_SETTINGS             32783
#define ID_UTILS_TUNING                 32784
#define ID_UTILS_TESTING                32785

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        139
#define _APS_NEXT_COMMAND_VALUE         32786
#define _APS_NEXT_CONTROL_VALUE         1226
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
